<a href="https://colab.research.google.com/github/Aaaaddddyyyyyyyy/Natural_Language_Processing-NLP-/blob/main/Bags_of_words.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

In [2]:
df= pd.DataFrame({'text':['people watch campusx','campusx watch campusx','people write comment','campusx write comment'],'output':[1,1,0,0]})

In [3]:
df

                    text  output
0   people watch campusx       1
1  campusx watch campusx       1
2   people write comment       0
3  campusx write comment       0

In [4]:
import pandas as pd
import numpy as np

In [5]:
df=pd.DataFrame({'text':['people watch campusx','campusx watch campusx','people write comment','campusx write comment'],'output':[1,1,0,0]})

In [6]:
df

                    text  output
0   people watch campusx       1
1  campusx watch campusx       1
2   people write comment       0
3  campusx write comment       0

In [7]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer()

In [8]:
bow= cv.fit_transform(df['text'])

In [9]:
print(cv.vocabulary_)     ## vocab

{'people': 2, 'watch': 3, 'campusx': 0, 'write': 4, 'comment': 1}

In [10]:
print(bow[0].toarray())
print(bow[1].toarray())

[[1 0 1 1 0]]
[[2 0 0 1 0]]

BAg of grams

In [11]:
df

                    text  output
0   people watch campusx       1
1  campusx watch campusx       1
2   people write comment       0
3  campusx write comment       0

In [12]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(ngram_range=(2,2))           ## 2,2= bi_gram  ### 3,3= tri_gram # 1,1= uni_gram

In [13]:
bow=cv.fit_transform(df['text'])

In [14]:
## vocab
print(cv.vocabulary_)

{'people watch': 2, 'watch campusx': 4, 'campusx watch': 0, 'people write': 3, 'write comment': 5, 'campusx write': 1}